query GetMovieInfo($id: ID!) {
  movieInfo(id: $id) {
    id
    backdrop_path
    poster_path
    title
    overview
    budget
    revenue
    vote_average
    release_date
    media_type
    similar {
      results {
        id
        title
        release_date
        poster_path
        media_type
      }
    }
  }
}

query GetTvShowInfo($id: ID!) {
  tvShowInfo(id: $id) {
    id
    backdrop_path
    poster_path
    title
    overview
    number_of_episodes
    number_of_seasons
    vote_average
    release_date
    media_type
    similar {
      results {
        id
        title
        release_date
        poster_path
        media_type
      }
    }
  }
}

query GetMovies {
  upcoming {
    total_pages
    page
    results {
      id
      title
      release_date
      poster_path
    }
  }
  topRated {
    total_pages
    page
    results {
      id
      title
      vote_average
      poster_path
    }
  }
}

query GetUpcoming($page: Int) {
  upcoming(page: $page) {
    total_pages
    page
    results {
      id
      title
      release_date
      poster_path
    }
  }
}

query GetTopRated($page: Int) {
  topRated(page: $page) {
    total_pages
    page
    results {
      id
      title
      vote_average
      poster_path
    }
  }
}

query GetMoviesSearch($query: String!, $pageSize: Int) {
  moviesSearch(query: $query, pageSize: $pageSize) {
    results {
      id
      title
      media_type
    }
  }
}
