export { default as ErrorMessage } from './ErrorMessage';
export { default as Favorites } from './Favorites';
export { default as MoviesBox } from './MoviesBox';
export { default as Pagination } from './Pagination';
export { default as Header } from './Header';
export { default as FavoritesCard } from './FavoritesCard';
export { default as MovieCard } from './MovieCard';
export { default as SearchBar } from './SearchBar';
export { default as MovieInfo } from './MovieInfo';
